make the GHA conda hack even hackier
This part of the code fails because for certain runner environments
there is no conda in the bin, this step should allow us to ignore this
failing step and test the differing architectures

diff --git a/.github/workflows/test_suite.yml b/.github/workflows/test_suite.yml
--- a/.github/workflows/test_suite.yml
+++ b/.github/workflows/test_suite.yml
@@ -26,7 +26,10 @@ jobs:
     #   if: runner.os == 'macOS'
 
     - name: HACK! remove default conda
-      run: sudo unlink /usr/bin/conda
+      run: |
+        set +e  # allow this step to fail for differing architectures/missing condas 
+        sudo unlink /usr/bin/conda
+        set -e  # reset
 
     - name: Install IC
       run: |
